
# TP Pokemon première partie

## Modules necessaires
* PANDAS 0.24.2  => Permet la manipulation et l'analyse de données
* NUMPY 1.16.3   => Permet la manipulation de tableaux et matrices

Dans ce TP, nous allons découvrir à travers un cas pratique les premières étapes pour mener à bien un projet de Machine Learning. Cet exemple permet d'aborder un large panel de techniques propres au Machine Learning et à l'analyse de données.

## L'univers des Pokémons

Un Pokémon est un animal issu du monde des jeux vidéo. Chaque Pokémon possède des caractéristiques qui lui sont propres, à savoir son type (Pokémon d'herbe, Pokémon de feu ... ) lui donnant alors des facultés spéciales. Ainsi, le Pokémon nommé `Dracofeu`, de type `Feu` est capable de cracher du feu. De plus, on note l'existence de Pokémons légendaires très rares et très puissants (Pokémon diamant, Pokémon platine...).

Les Pokémons sont également de différentes générations faisant référence à l'évolution de l'univers des Pokémons. Les Pokémons de première génération sont ceux ayant pris naissance au tout début de la création de l'univers (création de 151 Pokémons) pour arriver à la huitième génération avec plus de 800 Pokémons (2020)!

Dans cet univers viennent ensuite les dresseurs de Pokémons. Les dresseurs les collectionnent et les élèvent dans le but de les faire combattre entre eux jusqu'au KO. Lors d'un combat de Pokémons, opposant deux dresseurs, l'un choisit l'animal qui sera le premier à entrer dans l'arène. En fonction de ce premier Pokémon, le second dresseur choisit un animal dans sa collection qui sera en mesure de battre le premier Pokémon. Si le premier Pokémon présent dans l'arène est de type feu, il y a de fortes chances que le Pokémon choisi par l'adversaire soit de type eau afin de contrer les attaques du premier.

Cela nécessite pour le dresseur d'avoir une bonne connaissance de chaque Pokémon pour choisir celui qui pourra devenir vainqueur du combat. Pour l'aider dans son choix, les caractéristiques des Pokémons sont répertoriées dans un document appelé Pokédex.

# Mission : choisir le bon Pokémon!

En tant que dresseurs de Pokémon du 21e siècle, on vous demande de faire appel au Machine Learning pour faire le bon choix de Pokémon et ainsi gagner nos combats. Pour cela, vous pouvez vous appuyer sur des données en provenance du Pokédex, mais aussi sur des données issues des différents combats afin de trouver le bon modèle de prédiction qui pourra alors nous assurer une victoire lors de chaque bataille!


# Des données pour un apprentissage supervisé

## Des données basées sur l'expérience

Le Machine Learning est basé sur l'utilisation de données afin de permettre à notre ordinateur d'apprendre et de pouvoir réaliser des prédictions. Ces données doivent être en relation avec la mission qui nous est confiée et basée sur l'expérience. Dans notre cas, l'expérience consiste à connaître les issues de combats de Pokémons.


## Disposer d'un grand nombre de données d'apprentissage

Une machine n'est pas capable d'apprendre sur un petit jeu de données, car elle doit pouvoir étudier toutes les possibilités pour réaliser ses prédictions. Par conséquent, plus le nombre de cas d'études pour résoudre un problème est important, plus les prédictions seront précises.

## Des données d'apprentissage et des données de tests

Tout comme l'être humain, il est nécessaire de valider l'apprentissage de la machine afin de pouvoir corriger les écarts d'apprentissage (appelés biais) et ajuster ou modifier le modèle d'apprentissage. Pour cela, nous avons besoin de données d'apprentissage et de données de tests.

# Les étapes à réaliser pour mener à bien un projet de Machine Learning

Mener à bien un projet de Machine Learning consiste à réaliser six étapes consécutives :

1. Définition du problème à résoudre
2. Acquisition des données d'apprentissages et de tests
3. Préparer et nettoyer les données
4. Analyser, explorer les données
5. Choisir un modèle d'apprentissage
6. Visualiser les résultats, et ajuster ou modifier le modèle d'apprentissage

La phase de préparation des données est la plus importante dans un projet de Machine Learning, car en tant qu'humains, nous devons essayer de trouver les données les plus intéressantes qui nous permettront de répondre au problème donné.

Bien plus qu'une simple analyse des données, il faut déterminer comment il nous est possible de résoudre manuellement le problème, à partir des informations dont nous disposons, avant de le confier à la machine.
Ainsi, un même jeu de données peut être exploité différemment en fonction du problème donné.

# Étape 1 : définir le problème à résoudre

- Donner une défintion du problème à résoudre.

# Étape 2: acquérir des données d'apprentissage et de tests

- Importer les librairies `OS` et `pandas`

- Télécharger et copier les fichiers comportant les données nécessaires à la résolution du problème : 
1. Le fichier Pokedex.csv contient la liste des Pokémons et leurs caractéristiques. 
2. Le fichier Combats.csv est la base de connaissance et d'apprentissage, car il contient une liste de combats de Pokémons et le résultat de chacun d'entre eux. 
3. Enfin, le fichier tests.csv permettra de valider le modèle d'apprentissage.

- Affichier la liste des fichiers dans le repértoire du projet

# Étape 3 : préparation des données

Dans cette troisième étape, l'objectif est de réaliser une lecture approfondie des données afin de comprendre leur rôle et les impacts qu'elles peuvent avoir dans notre objectif de prédiction. C'est une sorte résolution manuelle du problème en formulant des hypothèses et en essayant de sélectionner les données qui répondront à celles-ci.

L'étude des données passe notamment par leur description (nom, type...), ainsi que par divers processus de traitement tels que le nettoyage (suppression des données inutiles, recherche des données manquantes) et enfin la combinaison entre elles, aussi appelée agrégation, dans le but de disposer d'un jeu de connaissances (observations) utilisables et appropriées à l'apprentissage et à l'atteinte de notre objectif.

## De quelles données disposons-nous?

#### - Quelle est la structure des données? 
#### - Afficher les 10 premières lignes
#### - Quelles sont les features de catégorisation?
#### - Est-ce qu'il existe des données de cétégorisation ordinale? 
#### - Préciser dans un tableau le type des données. 
#### - Quel est l'intérêt de connaitre les features de catégorisation?
#### - Quelles données sont de type numérique (Préciser discrètes ou continues)? 
#### - Pourquoi il est important de les connaitre?
#### - Que faut-il penser de la feature LEGENDAIRE?
#### - Transformer la feature $Legendaire$ en entier 0= FAUX et 1=VRAI
#### - Combien avons-nous d'observations?
#### - Afficher une description des données.
#### - Afficher les informations le jeu de données
#### - Manque-t-il des données? Si oui, discuter. 

### Recherche des features manquantes

####  - Chercher le Pokemon dont le nom est manquant
####  - Comment traiter les observations manquantes?

# Partie 2

##  Observations des combats

#### - Refaire les étapes précédentes pour analyser les observation sur les combats (fichier `combats.csv`) :

- Chargement du fichier
- Affichage des features
- Affichage des dix premières observations
- Classement des features: donnée catégorielle, numérique continue ou numérique discrète
- 10 premières lignes, Comptage du nombre d'observations, affichage des informations  et recherche d'éventuelles données absentes

#### - Discuter les résultats de l'analyse


#### - Calucler le nombre de combats menés par chaque Pokémon
Lors d'un combat, un Pokémon peut être utilisé en première position ou en seconde position.

#### - Calucler le nombre de combats gagnés par chaque Pokémon 

#### Faire l'assemblage des observations

#### Quel est le Pockémon qui a gagné le plus de combats? 

#### Existe-t-il des Pokémons n'ayant jamais gagné?

# Partie 3

## Agrégation des données avec le Pokédex

Cette agrégation va nous permettre d'avoir une vue centralisée des données et de permettre une analyse plus approfondie.

#### - Créer une liste comportant :
- Les numéros des Pokémons
- Le nombre de combats menés
- Le nombre de combats gagnés
- Le pourcentage de victoires par rapport au nombre de combats menés

#### - Créer un nouveau Pokedex comportant les noms de Pokemons et leur victoire

PARTIE 01

In [2]:
# Importer les librairies OS et pandas
import os
import pandas as pd
import numpy as np

# Définir le chemin vers le dossier 'data'
data_folder = 'data'

# Liste des fichiers CSV
pokedex_file = os.path.join(data_folder, 'pokedex.csv')
combats_file = os.path.join(data_folder, 'combats.csv')
tests_file = os.path.join(data_folder, 'tests.csv')

In [3]:
# Affichage de la liste des fichiers dans le répertoire 'data'
print("Fichiers disponibles dans le dossier 'data':")
for file in os.listdir(data_folder):
    print(file)

Fichiers disponibles dans le dossier 'data':
combats copy.csv
combats.csv
pokedex.csv
pokedexOld.csv
tests.csv

In [63]:
# Chargement des fichiers CSV dans des DataFrames
df_pokedex = pd.read_csv(pokedex_file,sep=';')
df_combats = pd.read_csv(combats_file)
df_tests = pd.read_csv(tests_file)

In [16]:
print("--- Analyse du DataFrame Pokedex (df_pokedex) ---")

# Quelle est la structure des données? Afficher les 10 premières lignes

print("\nStructure des données (10 premières lignes de df_pokedex):")
print(df_pokedex.head(10))

--- Analyse du DataFrame Pokedex (df_pokedex) ---

Structure des données (10 premières lignes de df_pokedex):
   NUMERO               NOM TYPE_1  TYPE_2  POINTS_DE_VIE  POINTS_ATTAQUE  \
0       1        Bulbizarre  Herbe  Poison             45              49
1       2        Herbizarre  Herbe  Poison             60              62
2       3        Florizarre  Herbe  Poison             80              82
3       4   Mega Florizarre  Herbe  Poison             80             100
4       5         Salamèche    Feu     NaN             39              52
5       6         Reptincel    Feu     NaN             58              64
6       7         Dracaufeu    Feu     Vol             78              84
7       8  Mega Dracaufeu X    Feu  Dragon             78             130
8       9  Mega Dracaufeu Y    Feu     Vol             78             104
9      10          Carapuce    Eau     NaN             44              48

   POINTS_DEFFENCE  POINTS_ATTAQUE_SPECIALE  POINT_DEFENSE_SPECIALE  \
0               49                       65                      65
1               63                       80                      80
2               83                      100                     100
3              123                      122                     120
4               43                       60                      50
5               58                       80                      65
6               78                      109                      85
7              111                      130                      85
8               78                      159                     115
9               65                       50                      64

   POINTS_VITESSE  NOMBRE_GENERATIONS LEGENDAIRE
0              45                   1       FAUX
1              60                   1       FAUX
2              80                   1       FAUX
3              80                   1       FAUX
4              65                   1       FAUX
5              80                   1       FAUX
6             100                   1       FAUX
7             100                   1       FAUX
8             100                   1       FAUX
9              43                   1       FAUX

In [17]:
# Quelles sont les features de catégorisation?
# Est-ce qu'il existe des données de catégorisation ordinale?
# Préciser dans un tableau le type des données.

print("\nInformations sur les types de données et catégorisation (df_pokedex):")
df_pokedex.info()
print(df_pokedex.shape)

Informations sur les types de données et catégorisation (df_pokedex):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NUMERO                   800 non-null    int64
 1   NOM                      799 non-null    object
 2   TYPE_1                   800 non-null    object
 3   TYPE_2                   413 non-null    object
 4   POINTS_DE_VIE            800 non-null    int64
 5   POINTS_ATTAQUE           800 non-null    int64
 6   POINTS_DEFFENCE          800 non-null    int64
 7   POINTS_ATTAQUE_SPECIALE  800 non-null    int64
 8   POINT_DEFENSE_SPECIALE   800 non-null    int64
 9   POINTS_VITESSE           800 non-null    int64
 10  NOMBRE_GENERATIONS       800 non-null    int64
 11  LEGENDAIRE               800 non-null    object
dtypes: int64(8), object(4)
memory usage: 75.1+ KB
(800, 12)

In [48]:
print("\nRésumé des types de features pour df_pokedex:")
print("Catégorielles (nominal) : #Name, Type 1, Type 2, Legendary")
print("Catégorielles (ordinale) : nombre_generation")
print("Numériques (discrètes) : point_de_vie,points_attaque,points_defense,points_attaque_speciale,points_defense_speciale,points_vitesse,")
print("Numériques (continues) : Aucune dans ce jeu de données.")

Résumé des types de features pour df_pokedex:
Catégorielles (nominal) : #Name, Type 1, Type 2, Legendary
Catégorielles (ordinale) : nombre_generation
Numériques (discrètes) : point_de_vie,points_attaque,points_defense,points_attaque_speciale,points_defense_speciale,points_vitesse,
Numériques (continues) : Aucune dans ce jeu de données.

In [22]:
print("Valeurs uniques de 'Legendary':", df_pokedex['LEGENDAIRE'].unique())

Valeurs uniques de 'Legendary': ['FAUX' 'VRAI']

In [39]:
# Compter le nombre de faux et de vrai dans la colonne 'LEGENDAIRE'
nombre_faux_vrai = df_pokedex['LEGENDAIRE'].value_counts()
print(f"Nombre de FAUX (0): {nombre_faux_vrai.get(0, 0)}")
print(f"Nombre de VRAI (1): {nombre_faux_vrai.get(1, 0)}")

Nombre de FAUX (0): 800
Nombre de VRAI (1): 0

In [47]:
# Transformer la feature LEGENDAIRE en entier 0= FAUX et 1=VRAI
print("\nTransformation de la feature 'LEGENDAIRE' en 0/1:")
df_pokedex['LEGENDAIRE'] = df_pokedex['LEGENDAIRE'].fillna('FAUX').map({'FAUX': 0, 'VRAI': 1})
print(df_pokedex[['NUMERO', 'NOM', 'LEGENDAIRE']].head(10))

Transformation de la feature 'LEGENDAIRE' en 0/1:
   NUMERO               NOM  LEGENDAIRE
0       1        Bulbizarre           0
1       2        Herbizarre           0
2       3        Florizarre           0
3       4   Mega Florizarre           0
4       5         Salamèche           0
5       6         Reptincel           0
6       7         Dracaufeu           0
7       8  Mega Dracaufeu X           0
8       9  Mega Dracaufeu Y           0
9      10          Carapuce           0

In [52]:
# Combien avons-nous d'observations?
print(f"\nNombre d'observations dans df_pokedex : {len(df_pokedex)}")

# Afficher une description des données.
df_pokedex.describe()

Nombre d'observations dans df_pokedex : 800

,NUMERO,POINTS_DE_VIE,POINTS_ATTAQUE,POINTS_DEFFENCE,POINTS_ATTAQUE_SPECIALE,POINT_DEFENSE_SPECIALE,POINTS_VITESSE,NOMBRE_GENERATIONS,LEGENDAIRE
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000,800.0
mean,400.5000,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375,0.0
std,231.0844,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129,0.0
min,1.0000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000,0.0
25%,200.7500,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000,0.0
50%,400.5000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000,0.0
75%,600.2500,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000,0.0
max,800.0000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000,0.0

In [ ]:
# Afficher les informations le jeu de données (déjà fait avec .info())
# Manque-t-il des données? Si oui, discuter.
print("\nRecherche de données manquantes (df_pokedex):")
missing_data = df_pokedex.isnull().sum()
print(missing_data[missing_data > 0])

Recherche de données manquantes (df_pokedex):
NOM         1
TYPE_2    387
dtype: int64

In [54]:
print("\nDiscussion sur les données manquantes:")
if missing_data.sum() == 0:
    print("Il n'y a pas de données manquantes dans le DataFrame 'df_pokedex'.")
else:
    print("Des données manquantes sont présentes. Nous devons décider comment les traiter : imputation (remplacer par la moyenne, médiane, mode), suppression des lignes/colonnes, etc.")

Discussion sur les données manquantes:
Des données manquantes sont présentes. Nous devons décider comment les traiter : imputation (remplacer par la moyenne, médiane, mode), suppression des lignes/colonnes, etc.

In [58]:
# Chercher le Pokémon dont le nom est manquant (s'il y en a un)
# En se basant sur l'output de df_pokedex.info() ou isnull().sum(), s'il y avait des NaNs dans 'Name'
print("\nRecherche de Pokémon avec un nom manquant (df_pokedex):")
pokemon_name_missing = df_pokedex[df_pokedex['NOM'].isnull()]
if not pokemon_name_missing.empty:
    print("Pokémon(s) avec un nom manquant:\n", pokemon_name_missing)
else:
    print("Aucun Pokémon avec un nom manquant.")

# Comment traiter les observations manquantes?
print("\nComment traiter les observations manquantes (stratégies générales):")
print("1. Suppression des lignes/colonnes : Si le nombre de valeurs manquantes est faible ou si la colonne entière n'est pas pertinente.")
print("2. Imputation : Remplacer les valeurs manquantes par une valeur calculée (moyenne, médiane, mode) ou une valeur spécifique (ex: 'Unknown', 0).")
print("   - Pour les données numériques : Moyenne, médiane (moins sensible aux outliers).")
print("   - Pour les données catégorielles : Mode (valeur la plus fréquente) ou une nouvelle catégorie 'Manquant'.")
print("3. Modèles d'imputation : Utiliser des modèles plus avancés pour prédire les valeurs manquantes (ex: K-NN Imputer).")
print("\nDans notre cas, pour 'Type 2', l'absence de valeur signifie l'absence de second type. On peut le remplir avec 'None' ou une chaîne vide, ou le laisser NaN et voir comment le modèle gère cela après encodage.")

# Traitement spécifique pour 'Type 2' : Remplacer les NaN par 'None' pour une meilleure clarté
df_pokedex['TYPE_2'].fillna('None', inplace=True)
print("\n'Type 2' après traitement des valeurs manquantes:")
print(df_pokedex[['NOM', 'TYPE_1', 'TYPE_2']].head(10))

Recherche de Pokémon avec un nom manquant (df_pokedex):
Pokémon(s) avec un nom manquant:
     NUMERO  NOM  TYPE_1 TYPE_2  POINTS_DE_VIE  POINTS_ATTAQUE  \
62      63  NaN  Combat   None             65             105

    POINTS_DEFFENCE  POINTS_ATTAQUE_SPECIALE  POINT_DEFENSE_SPECIALE  \
62               60                       60                      70

    POINTS_VITESSE  NOMBRE_GENERATIONS  LEGENDAIRE
62              95                   1           0

Comment traiter les observations manquantes (stratégies générales):
1. Suppression des lignes/colonnes : Si le nombre de valeurs manquantes est faible ou si la colonne entière n'est pas pertinente.
2. Imputation : Remplacer les valeurs manquantes par une valeur calculée (moyenne, médiane, mode) ou une valeur spécifique (ex: 'Unknown', 0).
   - Pour les données numériques : Moyenne, médiane (moins sensible aux outliers).
   - Pour les données catégorielles : Mode (valeur la plus fréquente) ou une nouvelle catégorie 'Manquant'.
3. Modèles d'imputation : Utiliser des modèles plus avancés pour prédire les valeurs manquantes (ex: K-NN Imputer).

Dans notre cas, pour 'Type 2', l'absence de valeur signifie l'absence de second type. On peut le remplir avec 'None' ou une chaîne vide, ou le laisser NaN et voir comment le modèle gère cela après encodage.

'Type 2' après traitement des valeurs manquantes:
                NOM TYPE_1  TYPE_2
0        Bulbizarre  Herbe  Poison
1        Herbizarre  Herbe  Poison
2        Florizarre  Herbe  Poison
3   Mega Florizarre  Herbe  Poison
4         Salamèche    Feu    None
5         Reptincel    Feu    None
6         Dracaufeu    Feu     Vol
7  Mega Dracaufeu X    Feu  Dragon
8  Mega Dracaufeu Y    Feu     Vol
9          Carapuce    Eau    None

PARTIE 02

In [59]:
print("\n--- Analyse du DataFrame Combats (df_combats) ---")

print("\nFeatures du DataFrame df_combats:", df_combats.columns.tolist())

--- Analyse du DataFrame Combats (df_combats) ---

Features du DataFrame df_combats: ['First_pokemon,Second_pokemon,Winner']

In [61]:
# Affichage des dix premières observations
print("\nDix premières observations de df_combats:")
print(df_combats.head(10))

Dix premières observations de df_combats:
  First_pokemon,Second_pokemon,Winner
0                         266,298,298
1                         702,701,701
2                         191,668,668
3                         237,683,683
4                         151,231,151
5                         657,752,657
6                         192,134,134
7                          73,545,545
8                         220,763,763
9                           302,31,31

In [ ]:
# Classement des features: donnée catégorielle, numérique continue ou numérique discrète
print("\nRésumé des types de features pour df_combats:")
df_combats.info()
print("Catégorielles : Aucune")
print("Numériques (discrètes) : First_pokemon, Second_pokemon, Winner")
print("Numériques (continues) : Aucune.")

Résumé des types de features pour df_combats:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   First_pokemon   50000 non-null  int64
 1   Second_pokemon  50000 non-null  int64
 2   Winner          50000 non-null  int64
dtypes: int64(3)
memory usage: 1.1 MB
Catégorielles : Aucune directement. 'First_pokemon', 'Second_pokemon', 'Winner' sont des IDs numériques mais représentent des catégories (les Pokémons). Ils seront traités comme des identifiants.
Numériques (discrètes) : First_pokemon, Second_pokemon, Winner
Numériques (continues) : Aucune.

In [ ]:
# Comptage du nombre d'observations
print(f"\nNombre d'observations dans df_combats : {len(df_combats)}")

# Recherche d'éventuelles données absentes
print("\nRecherche de données manquantes (df_combats):")
missing_combats_data = df_combats.isnull().sum()
print(missing_combats_data[missing_combats_data > 0])
if missing_combats_data.sum() == 0:
    print("Il n'y a pas de données manquantes dans le DataFrame 'df_combats'.")
else:
    print("Des données manquantes sont présentes dans 'df_combats'.")

Nombre d'observations dans df_combats : 50000

Recherche de données manquantes (df_combats):
Series([], dtype: int64)
Il n'y a pas de données manquantes dans le DataFrame 'df_combats'.

Calculer le nombre de combats menés par chaque Pokémon

In [68]:
# Un Pokémon peut être en première position ou en seconde position
combats_first = df_combats['First_pokemon'].value_counts()
combats_second = df_combats['Second_pokemon'].value_counts()

# Concaténer les deux séries et les sommer pour obtenir le nombre total de combats menés
nb_combats_menes = pd.concat([combats_first, combats_second], axis=0).groupby(level=0).sum()

print("\nNombre de combats menés par chaque Pokémon:")
print(nb_combats_menes.head())

Nombre de combats menés par chaque Pokémon:
1    133
2    121
3    132
4    125
5    112
Name: count, dtype: int64

In [69]:
nb_combats_gagnes = df_combats['Winner'].value_counts()

print("\nNombre de combats gagnés par chaque Pokémon:")
print(nb_combats_gagnes.head())

Nombre de combats gagnés par chaque Pokémon:
Winner
163    152
438    136
154    136
428    134
314    133
Name: count, dtype: int64

Faire l'assemblage des observations (Préparation pour l'agrégation)

In [71]:
# Créer un DataFrame pour les statistiques de combat
df_stats_combats = pd.DataFrame({
    'Pokemon_ID': df_pokedex['NUMERO'].unique() 
}).set_index('Pokemon_ID')

# Fusionner les nombres de combats menés et gagnés
df_stats_combats['Nb_Combats_Menes'] = nb_combats_menes
df_stats_combats['Nb_Combats_Gagnes'] = nb_combats_gagnes

# Remplacer les NaN (pour les Pokémon qui n'ont peut-être pas combattu ou gagné) par 0
df_stats_combats.fillna(0, inplace=True)

# Convertir en entier, car ce sont des comptages
df_stats_combats['Nb_Combats_Menes'] = df_stats_combats['Nb_Combats_Menes'].astype(int)
df_stats_combats['Nb_Combats_Gagnes'] = df_stats_combats['Nb_Combats_Gagnes'].astype(int)


print("\nStatistiques des combats par Pokémon (pré-agrégation):")
print(df_stats_combats.head())

Statistiques des combats par Pokémon (pré-agrégation):
            Nb_Combats_Menes  Nb_Combats_Gagnes
Pokemon_ID
1                        133                 37
2                        121                 46
3                        132                 89
4                        125                 70
5                        112                 55

In [72]:
pokemon_plus_victoires_id = df_stats_combats['Nb_Combats_Gagnes'].idxmax()
nb_victoires_max = df_stats_combats['Nb_Combats_Gagnes'].max()
pokemon_plus_victoires_name = df_pokedex[df_pokedex['NUMERO'] == pokemon_plus_victoires_id]['NOM'].iloc[0]

print(f"\nLe Pokémon qui a gagné le plus de combats est : {pokemon_plus_victoires_name} (ID: {pokemon_plus_victoires_id}) avec {nb_victoires_max} victoires.")

Le Pokémon qui a gagné le plus de combats est : Mewtwo (ID: 163) avec 152 victoires.

In [73]:
pokemon_jamais_gagnes = df_stats_combats[df_stats_combats['Nb_Combats_Gagnes'] == 0]

print("\nPokémons n'ayant jamais gagné de combat:")
if not pokemon_jamais_gagnes.empty:
    # Pour afficher les noms, nous devons fusionner avec df_pokedex
    pokemon_jamais_gagnes_names = df_pokedex[df_pokedex['NUMERO'].isin(pokemon_jamais_gagnes.index)]['NOM']
    print(pokemon_jamais_gagnes_names.tolist())
    print(f"Total de {len(pokemon_jamais_gagnes)} Pokémons n'ayant jamais gagné.")
else:
    print("Tous les Pokémons ont gagné au moins un combat.")

Pokémons n'ayant jamais gagné de combat:
['Tortank', 'Sabelette', 'Grodoudou', 'Ptitard', 'Empiflor', 'Magnéton', 'Métamorph', 'Migalos', 'Caratroc', 'Ursaring', 'Hariyama', 'Mega Latias', 'Corboss', 'Lianaja', 'Maracachi', 'Moyade', 'Pitrouille petite taille']
Total de 17 Pokémons n'ayant jamais gagné.

PARTIE 03 - Agrégation des données avec le Pokédex

In [75]:
print("\n--- Agrégation des données avec le Pokédex ---")

# Calcul du pourcentage de victoires
df_stats_combats['Pourcentage_Victoires'] = df_stats_combats.apply(
    lambda row: (row['Nb_Combats_Gagnes'] / row['Nb_Combats_Menes']) * 100 if row['Nb_Combats_Menes'] > 0 else 0,
    axis=1
)

# Réinitialiser l'index pour que 'Pokemon_ID' devienne une colonne normale
df_stats_combats.reset_index(inplace=True)
df_stats_combats.rename(columns={'Pokemon_ID': 'NUMERO'}, inplace=True) # Renommer pour la fusion

# Fusionner df_pokedex avec df_stats_combats
# Nous allons utiliser le 'NUMERO' (ID du Pokémon) comme clé de fusion
df_pokedex_agg = pd.merge(df_pokedex, df_stats_combats, on='NUMERO', how='left')

# Remplir les NaN résultant de la fusion (si un Pokémon du Pokedex n'a pas participé à un combat)
# Avec 0 pour les comptages et pourcentages
df_pokedex_agg['Nb_Combats_Menes'].fillna(0, inplace=True)
df_pokedex_agg['Nb_Combats_Gagnes'].fillna(0, inplace=True)
df_pokedex_agg['Pourcentage_Victoires'].fillna(0, inplace=True)

# Convertir en entier si nécessaire après remplissage
df_pokedex_agg['Nb_Combats_Menes'] = df_pokedex_agg['Nb_Combats_Menes'].astype(int)
df_pokedex_agg['Nb_Combats_Gagnes'] = df_pokedex_agg['Nb_Combats_Gagnes'].astype(int)

print("\nNouveau Pokédex agrégé avec les statistiques de combats (df_pokedex_agg):")
# Afficher les colonnes pertinentes pour vérifier
print(df_pokedex_agg[['NUMERO', 'NOM', 'Nb_Combats_Menes', 'Nb_Combats_Gagnes', 'Pourcentage_Victoires', 'LEGENDAIRE']].head())

print(f"\nDimensions du nouveau Pokédex agrégé : {df_pokedex_agg.shape}")

--- Agrégation des données avec le Pokédex ---

Nouveau Pokédex agrégé avec les statistiques de combats (df_pokedex_agg):
   NUMERO              NOM  Nb_Combats_Menes  Nb_Combats_Gagnes  \
0       1       Bulbizarre               133                 37
1       2       Herbizarre               121                 46
2       3       Florizarre               132                 89
3       4  Mega Florizarre               125                 70
4       5        Salamèche               112                 55

   Pourcentage_Victoires LEGENDAIRE
0              27.819549       FAUX
1              38.016529       FAUX
2              67.424242       FAUX
3              56.000000       FAUX
4              49.107143       FAUX

Dimensions du nouveau Pokédex agrégé : (800, 16)

C:\Users\acer\AppData\Local\Temp\ipykernel_11940\1182716562.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_pokedex_agg['Nb_Combats_Menes'].fillna(0, inplace=True)
C:\Users\acer\AppData\Local\Temp\ipykernel_11940\1182716562.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_pokedex_agg['Nb_Combats_Gagnes'].fillna(0, inplace=True)
C:\Users\acer\AppData\Local\Temp\ipykernel_11940\1182716562.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_pokedex_agg['Pourcentage_Victoires'].fillna(0, inplace=True)

In [76]:
df_pokedex_agg.head()

,NUMERO,NOM,TYPE_1,TYPE_2,POINTS_DE_VIE,POINTS_ATTAQUE,POINTS_DEFFENCE,POINTS_ATTAQUE_SPECIALE,POINT_DEFENSE_SPECIALE,POINTS_VITESSE,NOMBRE_GENERATIONS,LEGENDAIRE,index,Nb_Combats_Menes,Nb_Combats_Gagnes,Pourcentage_Victoires
0,1,Bulbizarre,Herbe,Poison,45,49,49,65,65,45,1,FAUX,0,133,37,27.819549
1,2,Herbizarre,Herbe,Poison,60,62,63,80,80,60,1,FAUX,1,121,46,38.016529
2,3,Florizarre,Herbe,Poison,80,82,83,100,100,80,1,FAUX,2,132,89,67.424242
3,4,Mega Florizarre,Herbe,Poison,80,100,123,122,120,80,1,FAUX,3,125,70,56.000000
4,5,Salamèche,Feu,NaN,39,52,43,60,50,65,1,FAUX,4,112,55,49.107143

In [77]:
df_pokedex_agg.info()
df_pokedex_agg.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NUMERO                   800 non-null    int64
 1   NOM                      799 non-null    object
 2   TYPE_1                   800 non-null    object
 3   TYPE_2                   413 non-null    object
 4   POINTS_DE_VIE            800 non-null    int64
 5   POINTS_ATTAQUE           800 non-null    int64
 6   POINTS_DEFFENCE          800 non-null    int64
 7   POINTS_ATTAQUE_SPECIALE  800 non-null    int64
 8   POINT_DEFENSE_SPECIALE   800 non-null    int64
 9   POINTS_VITESSE           800 non-null    int64
 10  NOMBRE_GENERATIONS       800 non-null    int64
 11  LEGENDAIRE               800 non-null    object
 12  index                    800 non-null    int64
 13  Nb_Combats_Menes         800 non-null    int64
 14  Nb_Combats_Gagnes        800 non-null    int64
 15  Pourcentage_Victoires    800 non-null    float64
dtypes: float64(1), int64(11), object(4)
memory usage: 100.1+ KB

,NUMERO,POINTS_DE_VIE,POINTS_ATTAQUE,POINTS_DEFFENCE,POINTS_ATTAQUE_SPECIALE,POINT_DEFENSE_SPECIALE,POINTS_VITESSE,NOMBRE_GENERATIONS,index,Nb_Combats_Menes,Nb_Combats_Gagnes,Pourcentage_Victoires
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000,800.0000,800.000000,800.000000,800.000000
mean,400.5000,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375,399.5000,125.000000,62.500000,49.088060
std,231.0844,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129,231.0844,21.130147,33.852141,26.244249
min,1.0000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000,0.0000,0.000000,0.000000,0.000000
25%,200.7500,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000,199.7500,120.000000,34.750000,27.419355
50%,400.5000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000,399.5000,127.000000,61.000000,47.928067
75%,600.2500,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000,599.2500,135.000000,90.000000,70.917793
max,800.0000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000,799.0000,164.000000,152.000000,98.449612

In [79]:
output_file_path = os.path.join(data_folder, 'pokedex_agrege.csv')
df_pokedex_agg.to_csv(output_file_path, index=False, sep=';')

Étape 4 : Préparation des données pour l'entraînement du modèle

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

print("--- Étape 4 : Préparation des données pour l'entraînement du modèle ---")
# --- 1. Fusion des caractéristiques des Pokémons avec les combats ---

# Fusionner df_combats avec df_pokedex_agg pour le First_pokemon
df_full_combats = pd.merge(df_combats, df_pokedex_agg,
                        left_on='First_pokemon', right_on='NUMERO',
                        how='left', suffixes=('_P1', None)) 

# Renommer les colonnes du Pokédex pour le premier Pokémon
df_full_combats.rename(columns={
    'NOM': 'Name_P1', 'Type 1': 'Type 1_P1', 'Type 2': 'Type 2_P1',
    'POINTS_DE_VIE': 'POINTS_DE_VIE_P1', 'POINTS_ATTAQUE': 'POINTS_ATTAQUE_P1',
    'POINTS_DEFENSE': 'POINTS_DEFENSE_P1', 'POINTS_ATTAQUE_SPECIALE': 'Sp_Atk_P1', 'POINT_DEFENSE_SPECIALE': 'Sp_Def_P1',
    'POINTS_VITESSE': 'Vitesse_P1', 'NOMBRE_GENERATIONS': 'NOMBRE_GENERATIONS_P1', 'LEGENDAIRE': 'Legendaire_P1',
    'Nb_Combats_Menes': 'Nb_Combats_Menes_P1', 'Nb_Combats_Gagnes': 'Nb_Combats_Gagnes_P1',
    'Pourcentage_Victoires': 'Pourcentage_Victoires_P1'
}, inplace=True)

# afficher les premières lignes pour vérifier
print("\nDataFrame après fusion avec le premier Pokémon (df_full_combats):")
print(df_full_combats.head())

# Supprimer la colonne redondante '#' après la fusion pour le P1
df_full_combats.drop(columns=['NUMERO'], inplace=True)

--- Étape 4 : Préparation des données pour l'entraînement du modèle ---

DataFrame après fusion avec le premier Pokémon (df_full_combats):
   First_pokemon  Second_pokemon  Winner  NUMERO    Name_P1 TYPE_1  TYPE_2  \
0            266             298     298     266   Embrylex  Roche     Sol
1            702             701     701     702   Viridium  Herbe  Combat
2            191             668     668     191    Togetic    Fée     Vol
3            237             683     683     237    Limagma    Feu     NaN
4            151             231     151     151  Amonistar  Roche     Eau

   POINTS_DE_VIE_P1  POINTS_ATTAQUE_P1  POINTS_DEFFENCE  Sp_Atk_P1  Sp_Def_P1  \
0                50                 64               50         45         50
1                91                 90               72         90        129
2                55                 40               85         80        105
3                40                 40               40         70         40
4                70                 60              125        115         70

   Vitesse_P1  NOMBRE_GENERATIONS_P1 Legendaire_P1  index  \
0          41                      2          FAUX    265
1         108                      5          VRAI    701
2          40                      2          FAUX    190
3          20                      2          FAUX    236
4          55                      1          FAUX    150

   Nb_Combats_Menes_P1  Nb_Combats_Gagnes_P1  Pourcentage_Victoires_P1
0                  110                    25                 22.727273
1                  125                   112                 89.600000
2                  127                    30                 23.622047
3                  123                     4                  3.252033
4                  138                    49                 35.507246

In [ ]:
# Fusionner à nouveau pour le Second_pokemon
df_full_combats = pd.merge(df_full_combats, df_pokedex_agg,
                        left_on='Second_pokemon', right_on='NUMERO',
                        how='left', suffixes=(None, '_P2')) 

# Renommer les colonnes du Pokédex pour le premier Pokémon
df_full_combats.rename(columns={
    'NOM': 'Name_P2', 'Type 1': 'Type 1_P2', 'Type 2': 'Type 2_P2',
    'POINTS_DE_VIE': 'POINTS_DE_VIE_P2', 'POINTS_ATTAQUE': 'POINTS_ATTAQUE_P2',
    'POINTS_DEFENSE': 'POINTS_DEFENSE_P2', 'POINTS_ATTAQUE_SPECIALE': 'Sp_Atk_P2', 'POINT_DEFENSE_SPECIALE': 'Sp_Def_P2',
    'POINTS_VITESSE': 'Vitesse_P2', 'NOMBRE_GENERATIONS': 'NOMBRE_GENERATIONS_P2', 'LEGENDAIRE': 'Legendaire_P2',
    'Nb_Combats_Menes': 'Nb_Combats_Menes_P2', 'Nb_Combats_Gagnes': 'Nb_Combats_Gagnes_P2',
    'Pourcentage_Victoires': 'Pourcentage_Victoires_P2'
}, inplace=True)

# Supprimer la colonne redondante '#' après la fusion pour le P2
df_full_combats.drop(columns=['NUMERO'], inplace=True)

In [96]:
print("\nDataFrame complet des combats avec caractéristiques des deux Pokémons (premières 5 lignes):")
print(df_full_combats.head())
print(f"\nDimensions du DataFrame complet : {df_full_combats.shape}")

DataFrame complet des combats avec caractéristiques des deux Pokémons (premières 5 lignes):
   First_pokemon  Second_pokemon  Winner    Name_P1 TYPE_1  TYPE_2  \
0            266             298     298   Embrylex  Roche     Sol
1            702             701     701   Viridium  Herbe  Combat
2            191             668     668    Togetic    Fée     Vol
3            237             683     683    Limagma    Feu     NaN
4            151             231     151  Amonistar  Roche     Eau

   POINTS_DE_VIE_P1  POINTS_ATTAQUE_P1  POINTS_DEFFENCE  Sp_Atk_P1  ...  \
0                50                 64               50         45  ...
1                91                 90               72         90  ...
2                55                 40               85         80  ...
3                40                 40               40         70  ...
4                70                 60              125        115  ...

   POINTS_DEFFENCE_P2  Sp_Atk_P2  Sp_Def_P2 Vitesse_P2  NOMBRE_GENERATIONS_P2  \
0                  40         60         40         60                      3
1                  90         72         90        108                      5
2                  75        125         95         40                      5
3                  90         60         90         48                      5
4                 230         10        230          5                      2

   Legendaire_P2  index_P2  Nb_Combats_Menes_P2 Nb_Combats_Gagnes_P2  \
0           FAUX       297                  113                   48
1           VRAI       700                  123                  105
2           FAUX       667                  134                   21
3           FAUX       682                  140                   39
4           FAUX       230                  135                    0

  Pourcentage_Victoires_P2
0                42.477876
1                85.365854
2                15.671642
3                27.857143
4                 0.000000

[5 rows x 113 columns]

Dimensions du DataFrame complet : (50000, 113)

In [97]:
# --- 2. Définition de la cible (y) ---
# La cible est 1 si First_pokemon est le Winner, 0 si Second_pokemon est le Winner
df_full_combats['Winner_Is_P1'] = (df_full_combats['Winner'] == df_full_combats['First_pokemon']).astype(int)

In [107]:
# --- 3. Définition des features (X) et de la cible (y) ---
# Nous allons exclure les IDs de Pokémon et le Winner original de nos features
features_to_drop = ['First_pokemon', 'Second_pokemon', 'Winner', 'Name_P1', 'Name_P2']
X = df_full_combats.drop(columns=features_to_drop + ['Winner_Is_P1'])
y = df_full_combats['Winner_Is_P1']

In [108]:
print(f"\nDimensions de X (features) : {X.shape}")
print(f"Dimensions de y (cible) : {y.shape}")

Dimensions de X (features) : (50000, 104)
Dimensions de y (cible) : (50000,)

In [109]:
# Identification des colonnes catégorielles et numériques pour le prétraitement
categorical_features = [col for col in X.columns if 'Type' in col or 'NOMBRE_GENERATIONS' in col]

In [110]:
# Liste des vraies colonnes catégorielles à encoder avec OneHotEncoder
categorical_features_ohe = [col for col in X.columns if 'Type' in col] # 'Type 1_P1', 'Type 2_P1', 'Type 1_P2', 'Type 2_P2'
categorical_features_ohe.extend(['NOMBRE_GENERATIONS_P1', 'NOMBRE_GENERATIONS_P2']) # Ajouter les générations ici

In [111]:
numerical_features = X.select_dtypes(include=np.number).columns.tolist()

In [112]:
for col in ['Legendaire_P1', 'Legendaire_P2', 'NOMBRE_GENERATIONS_P1', 'NOMBRE_GENERATIONS_P2']:
    if col in numerical_features:
        numerical_features.remove(col)

In [ ]:
numerical_features = [
    'Attack_P1', 'Defense_P1', 'Sp_Atk_P1', 'Sp_Def_P1', 'Speed_P1',
    'Nb_Combats_Menes_P1', 'Nb_Combats_Gagnes_P1', 'Pourcentage_Victoires_P1',
    'Legendary_P1', 'NOMBRE_GENERATIONS_P1',
    'Total_P2', 'HP_P2', 'Attack_P2', 'Defense_P2', 'Sp_Atk_P2', 'Sp_Def_P2', 'Speed_P2',
    'Nb_Combats_Menes_P2', 'Nb_Combats_Gagnes_P2', 'Pourcentage_Victoires_P2',
    'Legendary_P2', 'NOMBRE_GENERATIONS_P2'
]

categorical_features = [
    'Type 1_P1', 'Type 2_P1',
    'Type 1_P2', 'Type 2_P2'
]